name: dependencies check
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: '1.18beta2'

      - name: install lian
        run: go install lucor.dev/lian@latest

      - name: Check license of dependencies against go.mod
        run: lian -d --allowed="Apache-2.0, BSD-2-Clause, BSD-3-Clause, MIT, ISC"